### ISSUE TITLE
Issue Installing Bundle

### ISSUE THREAD

**Issue by marco-dea** [catalinsanda/org.openhab.binding.solarman#2]
Hello.
I'm new to OpenHab and I'm trying to install this binding,
I've installed the jar file using the console and the command:

bundle:install <url>

The bundle is installed but not active and I receive the following error if I try to activare manually:

255 │ Installed │  80 │ 0.1.2                  │ openHAB Add-ons :: Bundles :: Solarman Binding

openhab> bundle:start 255

Error executing command: Error executing command on bundles:
        Error starting bundle 255: Could not resolve module: org.openhab.binding.solarman [255]
  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.5.0)(!(version>=2.0.0)))"

Any feedback?

Kind regards

**Comment by catalinsanda** [comment]
What version of OpenHAB are you using? This binding only works with the latest milestone version 4.0.0 M2.

Although you can definitely install the bundle via the Felix console, a maybe simpler installation process is to copy it in the addons folder.

**Comment by marco-dea** [comment]
Thanks for your quick replay 
I'm using 3.4.4 on Raspebrry. If it's only work on the milestone version, I'll update my server

**Comment by marco-dea** [comment]
Hello.
I've switched to Milestone version and installed the Binding using the command bundle:install.
Now it seems to be active (true bundle:list command ) but I can't find it on the Openhab web console

**Comment by catalinsanda** [comment]
I don't know if installing the addon via bundle install properly configures
the addon so it shows in the web console.
Why don't you just put it in the addons folder and let OpenHAB handle the
installation in the OSGi container.
If you do it like that it will show up in the Bindings section as installed.

**Comment by marco-dea** [comment]
I managed to activate the binding but I came across some configuration issue

To recap:
Invereter: AZZURRO 1PH HYD6000 ZSS (model ZM1ES060)
Logger: LSW3_15_FFFF_1.0.89R

I configured the Item in Openhab in this way:

Logger IP address
Logger port: 8899
Inverter type (sofar_lsw3 or sofar_hyd3k-6k)
Logger serial number
Refresh 60

I received the error "argument src is null"

From the log:
Handler SolarmanLoggerHandler tried updating the thing status although the handler was already disposed.
Unexpected control code in error response frame
Modbus frame is too short or empty

Thanks for helping

**Comment by catalinsanda** [comment]
Hi @marco-dea, 

The error was due to a copy/paste error in the README file. It should have been `sofar_hyd3k-6k-es` instead of `sofar_hyd3k-6k`, updated the README and added better logging when the binding is unable to find the definition file.

I've created a new version (v0.2.0) which adds support for additional / custom Modbus requests and works on OpenHAB 4.0.0M3, so you can play around and read additional registers which are not in the inverter definition.

Errors like:
```
2023-05-31 11:39:19.864 [ERROR] [arman.internal.SolarmanLoggerHandler] - Unexpected control code in error response frame
2023-05-31 11:39:19.865 [ERROR] [arman.internal.SolarmanLoggerHandler] - Modbus frame is too short or empty
```
are generated when the response of the inverter doesn't match what's expected and I've seen that usually happens when the ranges are touching on registers that are not readable.

You could try another inverter definition or, if that doesn't work, please enable logging by putting the line below in the OpenHAB shell:
```
log:set TRACE org.openhab.binding.solarman
``` 
and post here the request / response bytes from the logs.

**Comment by catalinsanda** [comment]
Looking at this video: https://www.youtube.com/watch?v=ok_zhD5k3u4 it seems that `sofar_hyd3k-6k-es` is the correct value for your inverter.

**Comment by catalinsanda** [comment]
Closing inactive issue.
